customhost = "employee.c4gehvhkqswz.us-east-1.rds.amazonaws.com"
customuser = "Cloud_g2"
custompass = "Cloud_g2"
customdb = "employee, leave_application , payroll, attendance"
custombucket = "tengwaileong-employee1"
customregion = "US East (N. Virginia) us-east-1"
